### ISSUE TITLE
Posts keep getting eaten

### ISSUE THREAD

**Issue by bungholemaster** [K1rakishou/Kuroba-Experimental#993] opened 2024-01-24 18:19 UTC
Often when I try to make a new thread, the post will go through "successfully" but then it opens up a random thread I didn't make and marks it as my own, with my original post disappearing. It will show up in my post history but it does not actually appear on the site and clicking it links to the random thread it marked earlier.

This only started happening recently, it seems like if you input a captcha wrong it triggers this instead of failing the captcha, but it also seems random.

**Comment by K1rakishou** [comment] 2024-01-27 09:44
Duplicate of https://github.com/K1rakishou/Kuroba-Experimental/issues/996

**Closed as completed by K1rakishou** 2024-01-27 09:44 UTC
Labels: duplicate
