### ISSUE TITLE
Notification won't go away

### ISSUE THREAD

**Issue by cuteasci** [K1rakishou/Kuroba-Experimental#540] opened 2021-08-30 13:06 UTC
After posting on 2ch, this notification won't go away on the next post so you need to close it manually  

![Screenshot_20210830-160046_Pixel_Launcher_1](https://user-images.githubusercontent.com/59581277/131343587-284f0b62-250f-4dde-af1e-0b309659c923.png)

**Comment by K1rakishou** [comment] 2021-08-30 16:04
The notification showing up again after an error had occurred after posting is not a bug you need to either close it by clicking it or swipe away to notification. The actual bug is that it's empty on your screenshot for some reason.

**Comment by cuteasci** [comment] 2021-08-30 20:45
I guess I figured out.

You press "send the post" button, the notification says  "error posting authentication required" and if you solve the captcha before the notification goes away it will stay.

**Comment by K1rakishou** [comment] 2021-08-30 20:49
Oh, thanks for the STR.

**Comment by K1rakishou** [comment] 2021-09-06 10:47
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/0ea1d74c544822b3401d21d9a2c3f4d2248c4325

**Closed as completed by K1rakishou** 2021-09-06 10:47 UTC
Labels: bug
