### ISSUE TITLE
Cloudflare check hangs

### ISSUE THREAD

**Issue by papa-dub** [K1rakishou/Kuroba-Experimental#864] opened 2023-02-10 01:44 UTC
trying to post on 4chan and Cloudflare browser check starts and hangs until the message about system Webview pops up, but I can't read the rest of the message.  Checked webview settings and nothing is different from when it was going through earlier today.  On Pixel 6, Android 13.  Cloudflare check issue started when was on previous security update and continues on the one just released as of Feb. 5th, whether on mobile network or wifi.

**Comment by Patient6038** [comment] 2023-02-10 02:52
Same issue. I'm on the same device and Android 13 as well.

**Comment by Kamil118** [comment] 2023-02-10 03:11
I'm having same issue on Realme GT 5G with Android 12.

**Comment by papa-dub** [comment] 2023-02-10 03:12
I checked WebView implementation in settings and Android System WebView is the only option and it is selected.  Checked the ASWV app in settings and it is nominal, checked Play Store for updates and there are none.

**Comment by K1rakishou** [comment] 2023-02-10 03:58
Ok, I have bad news for you. I just checked it myself and it just works™ for me.

**Comment by K1rakishou** [comment] 2023-02-10 04:00
Ohhh, I see. It works in the emulator but doesn't work on an actual phone.

**Comment by cordelia04m** [comment] 2023-02-10 05:43
Just FYI, Kuroba Lite also has this problem as well.

**Comment by danpsr** [comment] 2023-02-10 06:48
I have the same problem. Redmi Note 10 Pro on LineageOS, Android 13.

I tested the other webviews available on the Play Store too (beta, dev, canary). All of them hang on the check just like the normal one, except Canary, which just shows a blank page for some reason (but also hangs). 

Also tried clearing the cache, data, force closing the webview app. No dice.

**Comment by kulapik** [comment] 2023-02-10 09:59
Having the same issue, OnePlus Nord 2, Android 12

**Comment by baraa272** [comment] 2023-02-10 11:38
Same problem on Android 13 with updated WebView

**Comment by K1rakishou** [comment] 2023-02-10 12:47
To be honest, I have no idea why it doesn't work. Judging by the logs it gets stuck in an infinite cloudflare check loop. I tried doing pretty much the same thing Tachiyomi is doing (grabbing headers from a request and passing them into WebView when loading the checks) but it didn't change anything. Tachiyomi is also explicitly checks the current installed WebView version and refuses to do anything if it's major version is < 105. That's why I'm assuming that it's probably the outdated WebView thing. But some people claim that they have the latest webview and it still doesn't work. And it seems like not everyone is affected. At this point I can only hope that the issue resolves itself miraciuosly.

**Comment by Chownio** [comment] 2023-02-10 13:10
Tis a travesty.

**Comment by PuffyVulva** [comment] 2023-02-10 14:31
Hello same issue on Oppo find x3 android 13 as well (:

**Comment by bungholemaster** [comment] 2023-02-10 15:58
Same issue on an S20 FE, Android 12

![Screenshot_20230210-105651_Settings](https://user-images.githubusercontent.com/16147700/218137038-645af563-c4b5-4fb8-8710-4ad607553294.jpg)

Went and reinstalled WebView to make sure it's updated and it still persists.

**Comment by floppyD** [comment] 2023-02-10 16:27
@K1rakishou KurobaDev doesn't seem to be affected, so you might want to take a look at what it's doing.

**Comment by sneed23** [comment] 2023-02-10 17:06
bump

**Comment by sneed23** [comment] 2023-02-10 17:07
Having the same issue

**Comment by sneed23** [comment] 2023-02-10 17:18
bump

**Comment by hiemsmutus** [comment] 2023-02-10 18:59
Happening on galaxy s8+ with android 9 and system webview 109.0.5414.117.

**Comment by Federx8** [comment] 2023-02-10 19:34
same issue on redmi xiaomi note 8T, up to date webview

**Comment by Dan-Quokka** [comment] 2023-02-11 02:54
Having same issue since yesterday on Huawei P Smart (FIG-LX3) with android 9 and latest version of WebView.

Have to open threads on browser to post so it's not a network issue.

**Comment by keelhauler95** [comment] 2023-02-11 03:34
What fixed it for me was disabling "Allow OkHttp to use HTTP/2 protocol" under experimental settings. No idea why though.

**Comment by Patient6038** [comment] 2023-02-11 03:37
> What fixed it for me was disabling "Allow OkHttp to use HTTP/2 protocol" under experimental settings. No idea why though.

Sadly that didn't fix it for me

**Comment by Kamil118** [comment] 2023-02-11 03:39
Disabling "Allow OkHttp to use HTTP/2 protocol" does nothing for me.

**Comment by K1rakishou** [comment] 2023-02-11 04:00
>Allow OkHttp to use HTTP/2 protocol

This has nothing to do with WebView which is used to pass CloudFlare checks.

**Comment by sneed233** [comment] 2023-02-11 04:33
>Checking your browser before accessing [sys.4channel.org](http://sys.4channel.org/).
>This process is automatic. Your browser will redirect to your requested content shortly.

>Please allow up to 5 seconds...
![cuckflare](https://user-images.githubusercontent.com/125110259/218240077-9663a2a0-1d7d-4423-89bb-a64a8f0a0f2c.png)

**Comment by seniorm0ment** [comment] 2023-02-11 05:02
I'm on GrapheneOS and it also has issues.
Graphene uses Vanadium Web View if it matters.

**Comment by moffatman** [comment] 2023-02-11 05:18
As far as I can tell there is much more strict SSL fingerprinting applied now. User-agent spoofing will cause it to hang. You can reproduce it in chrome devtools very easily. KurobaEx uses a custom user-agent, KurobaDev does not. But I can't reproduce the fix in Chance yet. Will let you know if I find the trick.

**Comment by K1rakishou** [comment] 2023-02-11 05:53
@moffatman 
I mean, yes, there is a custom user-agent in the app but it's only used for posting on 4chan (because of weird shadow bans where your post doesn't appear on the site and also to load videos on 2ch.hk because of some other issue). In all the other cases the currently installed WebView's user agent is used.

See https://github.com/K1rakishou/Kuroba-Experimental/blob/develop/Kuroba/core-common/src/main/java/com/github/k1rakishou/common/AppConstants.kt#L30

And then it's used here 

https://github.com/K1rakishou/Kuroba-Experimental/blob/c16f4983dd6422013fe0624b5ea8e5fd4bb056a3/Kuroba/app/src/main/java/com/github/k1rakishou/chan/features/bypass/SiteFirewallBypassController.kt#L162

**Comment by K1rakishou** [comment] 2023-02-11 06:16
@moffatman 
Also, I just checked Kuroba's code and it seems like it uses a custom user agent to pass CloudFlare.

https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/net/NetUtils.java#L43

https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/net/CloudflareInterceptor.kt#L88

```
public class BuildConfigUtils {
    public static final String VERSION = BuildConfig.APP_LABEL + "/" + BuildConfig.VERSION_NAME;
}
```

Now this doesn't make any sense.

**Comment by moffatman** [comment] 2023-02-11 06:27
I just changed user-agent in Chance to the string `something`. Now it passes 🤣 . 
What I guess is happening, the check is more strict and webview doesn't pass when validating against a normal user-agent `Mozilla/5.0...`. But for some custom user-agent, there isn't anything expected, so it looks OK.

Although I cleared cookies and tried again, it hung again. I had to change the user-agent a subsequent time to `somethingnew`. May need to have some method of cycling the user-agent?

**Comment by K1rakishou** [comment] 2023-02-11 06:53
Changing user-agent to some random string actually doesn't work for me.

**Comment by K1rakishou** [comment] 2023-02-11 07:12
Even regular Kuroba doesn't work for me.

**Comment by moffatman** [comment] 2023-02-11 07:16
OK you may have some further issue with your IP. Also I realized a problem with setting a junk user-agent. It will let me pass cloudflare, but then the `/captcha` endpoint will always return a long cooldown. Need to find some user-agent which is accepted in both.

**Comment by Nekrolysis** [comment] 2023-02-11 13:27
Interesting find here after a quick google search. 

For some reason having Google Chrome installed, Disables the WebView app. If you disable the Chrome app, WebView re enables itself and allows me to pass the cloud flare check and post. Rather tedious but if you just HAVE to shitpost it's one way to get around it for the time being. 

I hope this info helps somehow.

Edit: I've got a Samsung Galaxy Note 8, WebView version 79.0.3945.116.

I wonder if its webview version dependent?

**Comment by PuffyVulva** [comment] 2023-02-11 14:56
Hello disabling chrome did not fix the issue for me
Seems you were just had a lucky fluke (:

**Comment by muddi900** [comment] 2023-02-11 14:56
> Interesting find here after a quick google search. 
> 
> For some reason having Google Chrome installed, Disables the WebView app. If you disable the Chrome app, WebView re enables itself and allows me to pass the cloud flare check and post. Rather tedious but if you just HAVE to shitpost it's one way to get around it for the time being. 
> 
> I hope this info helps somehow.

Disabling Chrome does not work for me. Pixel 6 on Android 13. WebView 109.0.5414.117.

**Comment by hiemsmutus** [comment] 2023-02-11 15:04
Chrome is disabled on my phone. I force-stopped fennec and chromium but that did not help. Koruba-dev still works.

**Comment by Nekrolysis** [comment] 2023-02-11 15:05
> 109.0.5414.117

Dang I was hoping I was on to something for the masses haha. Well maybe it can help the dev at least....right? D: 

I've got a Samsung Galaxy Note 8, WebView version 79.0.3945.116

**Comment by Dan-Quokka** [comment] 2023-02-11 15:18
> For some reason having Google Chrome installed, Disables the WebView app. 
> If you disable the Chrome app, WebView re enables itself and allows me to pass the cloud flare check and post.

Well you see I actually thought it was the opposite, when this problem began I already had chrome disabled so I enabled it again and this worked for me for a couple of hours but then it stopped working so I disabled chrome again but it hasn't worked since.

**Comment by Igoorx** [comment] 2023-02-12 16:20
3.19 works fine for me, 3.22 is broken. I think some change between these versions causes this issue.

**Comment by 1sad** [comment] 2023-02-12 17:48
same issue on android 10
rolling back webview, updating webveiw doesnt do anything

used webviewtest to see if it doesnt work just going to 4chan with webview, but it works, i can load captcha and post normally from webview outside of kurobaex, and in bromite i can get captcha too

i tried changing useragent to my desktop one, and it made webview not pass the check either.
but when i reverted default useragent webveiw passes the check again, but not in app

1.3.19 and 20 and 21 dont work for me, but the difference in 19 is that it gives me these errors, that the newer ones dont give
![image](https://user-images.githubusercontent.com/23120024/218327688-fa1c10f6-d6e1-4972-b88c-89a8e289cfb3.png)
this only once
then after restart i just kept getting these
![image](https://user-images.githubusercontent.com/23120024/218327716-c0291eca-3609-4f3d-a061-af5c0d06ec67.png)

also i noticed in 20, and 19 (not sure if in 21, kinda forgot) there is a cloudflare cookie setting you can manually put in the cookie string, in the sites>configure 4chan
in 22 there is no option like that, just 4chan cookie strings

also worth mentioning, some days ago (though im not sure if its a new or old issue), some archives (alice and archived.moe i think) started failing to load full images too, saying you need to pass the cloudflare check before loading fullscreen images, and there was no way to do that as far as im aware
opening them up in a browser worked just fine

**Comment by Patient6038** [comment] 2023-02-13 19:19
Not my post, just a suggestion from the /g/ discussion.

>I'm guessing the issue probably has nothing to do with Webview at all. I tried the latest version and even the canary beta one, no dice. Hell, even fucking with the flags doesn't do anything. Guessing it's a cookie thing. Wiping the app doesn't do anything either

**Comment by Dan-Quokka** [comment] 2023-02-14 04:48
Is it too early to declare this issue "unfixable"?

**Comment by K1rakishou** [comment] 2023-02-14 05:43
I added a new setting to use a custom user-agent. This seems to help me pass the CloudFlare check and load the captcha however I can't post because my IP is banned so I can't see whether the post actually appears in the thread or not. You have to check that yourself. Also you need to find the user-agent by yourself too. I tried using "KurobaEx/v1.2.3.4" and it seemed to work. You can find the setting in Experimental settings (it's the last one).

[KurobaEx-beta.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/10729155/KurobaEx-beta.zip)

**Comment by Dubsys** [comment] 2023-02-14 05:58
> I added a new setting to use a custom user-agent. This seems to help me pass the CloudFlare check and load the captcha however I can't post because my IP is banned so I can't see whether the post actually appears in the thread or not. You have to check that yourself. Also you need to find the user-agent by yourself too. I tried using "KurobaEx/v1.2.3.4" and it seemed to work. You can find the setting in Experimental settings (it's the last one).
> 
> [KurobaEx-beta.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/10729155/KurobaEx-beta.zip)

This completely fixes the issue for me, made up a useragent and it all works fine now.

**Comment by Dan-Quokka** [comment] 2023-02-14 06:17
> I added a new setting to use a custom user-agent. you need to find the user-agent by yourself too. I tried using "KurobaEx/v1.2.3.4" and it seemed to work. You can find the setting in Experimental settings (it's the last one).

> [KurobaEx-beta.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/10729155/KurobaEx-beta.zip)

This just fixed the problem, thank you so much.

**Comment by K1rakishou** [comment] 2023-02-14 06:29
Ok, seems it works. Gonna add some stuff that I wanted to add and then make a new release. You don't need to import/export anything, just wait for the next release (unless you are using the FDroid version, haha).

**Comment by K1rakishou** [comment] 2023-02-14 07:09
https://github.com/K1rakishou/Kuroba-Experimental/commit/4518c12d09d489258684269119017f55df6721fd

**Closed as completed by K1rakishou** 2023-02-14 07:09 UTC
Labels: enhancement

**Comment by Tairetsu** [comment] 2023-02-14 09:41
Thanks for the hard work. Setting the string to KurobaEx/v1.2.3.4 didn't work for some reason but KurobaEx alone did lol

**Comment by hiemsmutus** [comment] 2023-02-14 13:39
Setting the custom user-agent to KurobaEx/v1.2.3.4 works for me. Thank you for fixing this.
