### ISSUE TITLE
Cant post on /bant/

### ISSUE THREAD

**Issue by MaxTendency** [K1rakishou/Kuroba-Experimental#250] opened 2020-11-19 01:18 UTC
With KurobaEX I cant post on /bant/ , other boards seem to be working fine. It shows "post succesful" but the post doesn't actually post. On browser and kuroba (normal version) it works fine. Using the latest version and also tried both v2nojs and v2js captcha, still doesnt fix.

**Comment by K1rakishou** [comment] 2020-11-19 07:17
Duplicate of https://github.com/K1rakishou/Kuroba-Experimental/issues/249

**Closed as completed by K1rakishou** 2020-11-19 07:17 UTC
Labels: duplicate
