### ISSUE TITLE
thread download doesn't work

### ISSUE THREAD

**Issue by alexoleol** [K1rakishou/Kuroba-Experimental#689] opened 2021-12-28 11:42 UTC
For some reason thread archive/downloader doesn't work for me. It's only download the first message of a thread (OP). I tried it with 2ch.hk and fdroid app version

**Comment by K1rakishou** [comment] 2021-12-28 13:43
It may not work with 2ch.hk because of their anti-spam script that breaks a lot of stuff. Try passing the antispam checks (Captcha window -> Auth) and then start downloading a thread, it should work until the anti-spam cookie gets invalidated again (which usually takes ~12hours). This app doesn't support passing antispam checks automatically when the app is in background because it's a huge pain in the ass and only one site uses it. If it still doesn't work even after passing anti-spam checks then I will need your logs.

**Comment by alexoleol** [comment] 2021-12-28 14:41
> It may not work with 2ch.hk because of their anti-spam script that breaks a lot of stuff. Try passing the antispam checks (Captcha window -> Auth) and then start downloading a thread, it should work until the anti-spam cookie gets invalidated again (which usually takes ~12hours). This app doesn't support passing antispam checks automatically when the app is in background because it's a huge pain in the ass and only one site uses it. If it still doesn't work even after passing anti-spam checks then I will need your logs.

I got the issue. It was just because the thread is already archived now. For some reason, when I open it with your client - it's kinda didn't really redirect me to it, cause it's not completely understand that I'm on the other, archived page already. And it gives me link for the original thread, when I want to share it, but not archived one. And I think that's the same with thread downloading. It's ok, I think, that it saves original link, but thing with downloading should be fixed.
For example:
original thread link: https://2ch.hk/b/res/260035660.html
archived one: https://2ch.hk/b/arch/2021-12-22/res/260035660.html
for the normal browser it simply redirect to archived one, for your client it's just like the same, but not completely, and that's why downloading isn't working with archived pages, like it should be.
I suppose it's should be the same with any other boards which is have threads archives

**Comment by K1rakishou** [comment] 2021-12-28 15:11
Oh I see. Yeah this is most likely the cause of the bug.

**Comment by K1rakishou** [comment] 2021-12-29 14:42
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/d963465dc1dd2de4df612b92a26272901bd29aa7

**Closed as completed by K1rakishou** 2021-12-29 14:42 UTC
Labels: bug
