### ISSUE TITLE
acknowledge check fails constantly but posts still go through

### ISSUE THREAD

**Issue by gascoract** [K1rakishou/Kuroba-Experimental#997] opened 2024-01-26 11:32 UTC
Most times when I post I get the acknowledge fail but the post still goes through while not being marked as mine.

**Comment by K1rakishou** [comment] 2024-01-27 09:43
Duplicate of https://github.com/K1rakishou/Kuroba-Experimental/issues/996

**Closed as completed by K1rakishou** 2024-01-27 09:43 UTC
Labels: duplicate
