### ISSUE TITLE
App stucks on loading, then crashes.

### ISSUE THREAD

**Issue by lsvy97** [K1rakishou/Kuroba-Experimental#513] opened 2021-08-01 07:47 UTC
Redmi Note 9, Android 10, KurobaEx 0.11.12 > 0.11.13.
Thought updating would help, but it still doesn't load and crashes. Can't provide logs right now, will do when I'll get to my PC.
By the way, why the settings can't be accessed while loading catalog? It would be really helpful to get logs or turn off some thread watchers.

**Comment by lsvy97** [comment] 2021-08-01 08:05
And what does it loading even in airplane mode?

**Comment by lsvy97** [comment] 2021-08-01 08:08
Oh, it's loaded, here's the log:
https://pastebin.com/py267c1J

**Comment by K1rakishou** [comment] 2021-08-01 08:09
Yeah I will need logs.

>By the way, why the settings can't be accessed while loading catalog? It would be really helpful to get logs or turn off some thread watchers.

You should be able to access the settings, it may be slow because everything is being initialized.

>And what does it loading even in airplane mode?

It tries to connect to the server and if it fail it fallbacks to loading stuff from the database.

**Comment by K1rakishou** [comment] 2021-08-01 08:16
>java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 6467936 free bytes and 6316KB until OOM, target footprint 402653184, growth limit 402653184; failed due to fragmentation (largest possible contiguous allocation 0 bytes)

So it fails with OutOfMemory exception but it's impossible to say what's causing it. The fact that this happens right on the app start says that there is something very wrong going on but I can't tell what exactly just by the logs.

To fix this I will need your whole app backup (Settings -> Import/Export -> Export backup file). Don't post it here though, send it to my email. This is the only way for me to figure out what's wrong. It's fine if you refuse because there might be some threads/bookmarks that you may not want to share with anyone (and it's impossible to not export only those threads/bookmarks). But again, this is the only way, because these kinds of errors may happen at random places so it's impossible to just guess what's wrong.

**Comment by lsvy97** [comment] 2021-08-01 08:21
Well, it crashed again as I tried to send logs through the app, but I'll email backup when it loads again

**Comment by K1rakishou** [comment] 2021-08-01 08:25
Yeah it's still the OOMs

>E/(14:38:58.465) KurobaEx | ThreadBookmarkGroupEntryManager: loadThreadBookmarkGroupsInternal() error
E/(14:38:58.465) KurobaEx | ThreadBookmarkGroupEntryManager: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available

**Comment by K1rakishou** [comment] 2021-08-01 08:26
How many bookmarks do you have?

**Comment by lsvy97** [comment] 2021-08-01 08:56
A lot. Probably should enable auto-removal, but I always think that I'll read some threads later.

**Comment by K1rakishou** [comment] 2021-08-01 09:05
If it's more than one thousand then this may be the case because I have ever only tested it with 1 thousand bookmarks max. Then I will definitely need your backup because I might figure out how to optimize it properly for the large amount of bookmarks.

**Comment by lsvy97** [comment] 2021-08-01 09:24
> If it's more than one thousand then this may be the case because I have ever only tested it with 1 thousand bookmarks max. Then I will definitely need your backup because I might figure out how to optimize it properly for the large amount of bookmarks.

With OVER1000 bookmarks? Just as I decided to get rid of them. Ok, I'll try to back it up.

**Comment by K1rakishou** [comment] 2021-08-01 09:31
Yes I need the backup in the current state with thousands of bookmarks because if you clean them up then it may stop crashing so I won't be able to do anything.

**Comment by lsvy97** [comment] 2021-08-01 10:32
Remembered that I have an older backup that I did two months ago, but it has 1013 bookmarks and loads up pretty well on the clone version of the same app. So the issue is definitely with number of bookmarks. Still trying to load it for backup.

**Comment by lsvy97** [comment] 2021-08-01 13:07
Finally, it loaded, sent the backup to email

**Comment by K1rakishou** [comment] 2021-08-01 13:30
Thanks, I managed to reproduce the same OutOfMemory error so I'm gonna investigate what's going on now.

**Comment by K1rakishou** [comment] 2021-08-01 13:35
Oh yeaaah, now I see. So there is some kind of an error in the SQL query which does a lot of unnecessary stuff which results in loading 2.3 mln elements into the memory instead of 1.5k. No wonder it crashes with OOM. And apparently it's a really old bug because bookmark groups were introduced back in v0.2.11-beta. Yeah this is pretty embarassing.

![image](https://user-images.githubusercontent.com/10332458/127772818-c373a5b8-155e-4f7e-8dc7-672137c1d991.png)

**Comment by K1rakishou** [comment] 2021-08-01 13:54
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/75f6da4ad80e365157c41819937f9e69c470497a

**Comment by K1rakishou** [comment] 2021-08-01 13:55
Alright, I'm gonna give you an apk with the fix so you can check it out and make sure everything works as expected. I'm gonna release a new version with the fix tomorrow or maybe a day later. I guess this should fix issues for all the people who complain about slow app start times and all those weird OOMs that I've been seeing for months.

**Comment by K1rakishou** [comment] 2021-08-01 14:02
@lsvy97 Alright, here you go.

[KurobaEx.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/6912785/KurobaEx.zip)

**Comment by K1rakishou** [comment] 2021-08-01 14:04
I'm gonna close the issue because the bug is fixed if something is not working as expected then create a new issue.

**Closed as completed by K1rakishou** 2021-08-01 14:04 UTC
Labels: bug

**Comment by lsvy97** [comment] 2021-08-01 14:11
Aww yiss! It finally works!
