### ISSUE TITLE
Theme viewer has display bug showing blown up images on 1.1.6

### ISSUE THREAD

**Issue by Pentaphon** [K1rakishou/Kuroba-Experimental#634] opened 2021-11-15 18:07 UTC
See screenshot.  Slight theme viewer display bug on Tomorrow Night theme viewer where the image it is showing is blown up for some reason. 

![Screenshot_20211115-100312](https://user-images.githubusercontent.com/49374058/141832120-f45a7e0c-bb43-4278-8ac2-f7d8591dccd6.png)

**Comment by Pentaphon** [comment] 2021-11-15 18:11
Update: display bug jumps to different themes each time you open the image viewer. 

![Screenshot_20211115-101018](https://user-images.githubusercontent.com/49374058/141832868-d1e3fd07-d883-444e-915b-31f3edc1ea07.png)

**Comment by K1rakishou** [comment] 2021-11-16 15:51
It looks fine to me, weird.

**Comment by Pentaphon** [comment] 2021-11-16 15:52
> It looks fine to me, weird.

It may not show up for you sometimes but when you check each dark theme another time you will definitely see it. At least, I certainly do.

**Comment by K1rakishou** [comment] 2021-11-19 11:29
Still can't reproduce, but hopefully should be fixed by https://github.com/K1rakishou/Kuroba-Experimental/commit/56693707f6c7b43533b2a47b18e4a21b627554ab

**Comment by Pentaphon** [comment] 2021-12-01 15:20
Still happening in 1.1.6 latest commit. 

![Screenshot_20211201-071911](https://user-images.githubusercontent.com/49374058/144261653-68c4a651-6a6a-4fae-a747-26ff62a6f069.png)

**Comment by K1rakishou** [comment] 2021-12-01 16:07
That's weird.

**Comment by K1rakishou** [comment] 2021-12-08 13:57
Still can't reproduce, but hopefully it should be fixed now because the whole PostCell measure/layout logic was rewritten from scratch.

**Closed as completed by K1rakishou** 2021-12-08 13:57 UTC
Labels: bug
