### ISSUE TITLE
New video viewer is very buggy 

### ISSUE THREAD

**Issue by cuteasci** [K1rakishou/Kuroba-Experimental#717] opened 2022-01-11 20:20 UTC
1. The play button at the bottom doesn't work if you trying to play the video for the first time. You can play it by pressing the middle play button and after that the bottom button will work.
2. Position indicator at the seek bar doesn't move when video is started.
3. Sometimes the seek bar is either very dark or invisible.

**Comment by myilu** [comment] 2022-01-12 07:08
![Screenshot_20220112-020618.png](https://user-images.githubusercontent.com/78330494/149080202-56eb37f0-84fb-4759-a496-8edc1a617776.png)
I agree with everything OP said
Although, it isn't like that with every video. Most do work as intended.

**Comment by K1rakishou** [comment] 2022-01-12 11:11
1. Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/a9f5d9ced404ffb932b0a12ace6236bc03f07772
2. Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/c0560e85e3ec2f45c98c2a0f0fca5c435d01cadb
3. I don't get what you mean by that but it seems to be related to 2 and hopefully is fixed by https://github.com/K1rakishou/Kuroba-Experimental/commit/c0560e85e3ec2f45c98c2a0f0fca5c435d01cadb as well.

**Comment by cuteasci** [comment] 2022-01-14 21:28
You still sometimes  cant see the seek bar 
![IMG_20220115_002611](https://user-images.githubusercontent.com/59581277/149587545-b8114238-9839-4579-88b4-3e50d63cbcd7.jpg)
After pausing it appears

**Comment by cuteasci** [comment] 2022-01-17 00:00
Everything seem works fine in 1.3.3

**Comment by K1rakishou** [comment] 2022-01-20 13:09
Then I'm closing the issue.

**Closed as completed by K1rakishou** 2022-01-20 13:09 UTC
Labels: bug
