### ISSUE TITLE
New feature to solve the image load error

### ISSUE THREAD

**Issue by AntonioVOL** [K1rakishou/Kuroba-Experimental#535] opened 2021-08-24 00:19 UTC
I think the application should have this image viewer instead of the current one so that the images load properly.

the viewer that I propose is on the app 'Overchan (fork)'

is 'built-in library skia'

https://github.com/AliceCA/Overchan-Android

Pd: remove my issue of image not load properly please.

**Comment by K1rakishou** [comment] 2021-08-24 08:50
Android already uses Skia internally for drawing/bitmap decoding.
https://android.googlesource.com/platform/frameworks/base/+/7b2f8b8/core/jni/android/graphics/BitmapFactory.cpp

**Comment by AntonioVOL** [comment] 2021-08-24 21:14
Yeah, but Kuroba's application would work fine for me with that library to use it when loading images.

In the 'Overchan (fork)' app there is the option to disable or enable this library that I think they have integrated it or something like that.

please add the option to use this image viewer tool.

**Comment by K1rakishou** [comment] 2021-08-24 21:33
What's even the problem? Do you have logs/screenshots/videos of what's not working?

**Comment by AntonioVOL** [comment] 2021-08-25 11:54
A video that i made of the problem, the error dosent have logs

http://imgur.com/gallery/JnDEYmZ

**Comment by K1rakishou** [comment] 2021-08-25 12:12
Alright now I see. Is this the same error as in https://github.com/K1rakishou/Kuroba-Experimental/issues/519 ?

**Comment by K1rakishou** [comment] 2021-08-25 12:17
This won't fix the issue itself because the issue is most likely some kind of out of memory error, but at least it shouldn't hide the image when the tile load error is thrown anymore.

https://github.com/K1rakishou/Kuroba-Experimental/commit/d6708d75cc498bcf5ee2377bf433a1f7d4a4710d

**Closed as completed by K1rakishou** 2021-08-25 12:17 UTC
Labels: bug
